fix(export): fix missing $format parameter
Fatal error: Uncaught ArgumentCountError: Too few arguments to function buildRowsSelect(), 7 passed in /home/lobbywat/lobbydev/db_export.php on line 2267 and exactly 8 expected in /home/lobbywat/lobbydev/db_export.php:2599
Stack trace:
#0 /home/lobbywat/lobbydev/db_export.php(2267): buildRowsSelect('partei', 'v_partei', 'v_partei', Array, Array, Array, 0)
#1 /home/lobbywat/lobbydev/db_export.php(2364): getSqlData('0', Array, 'lobbywat_lobbyw...', 1, Array, Object(CsvExporter), Object(PDO))
#2 /home/lobbywat/lobbydev/db_export.php(2033): export_tables(Object(CsvExporter), Array, NULL, NULL, 1, 'lobbywat_lobbyw...', 'export', Array, '\n', 'file', 'multi_file', NULL, NULL, NULL, Array, Object(PDO), Array)
#3 /home/lobbywat/lobbydev/db_export.php(1883): export(Object(CsvExporter), 'lobbywat_lobbyw...', 'export', Array, '\n', 'multi_file', NULL, Object(PDO))
#4 /home/lobbywat/lobbydev/db_export.php(2875): main()
#5 {main}
  thrown in /home/lobbywat/lobbydev/db_export.php on line 2599