pg_create_delta: strip more placeholders
some names of parliamentary groups lack italian translations. Instead there might be a placeholder like ' ()' or '-- ()'.
If these placeholders are not normalized (that is, removed) we end up matching placeholders against each other, which is undesirable.

This change should resolve the following situation with two groups sharing the same placeholder

Swiss Oldtimers - Kulturgut Historische Strassenfahrzeuge ()
Swiss Oldtimers - patrimoine culturel des véhicules routiers historiques ()
-- ()

and

Kindes- und Erwachsenenschutz ()
Protection de l'enfant et de l'adulte ()
-- ()

which lead to the following error

AssertionError: DATA INTEGRITY FAILURE: There are multiple possibilities in the database for organisation 'Kindes- und Erwachsenenschutz: [(7597, 0, 'Parlamentarische Gruppe'), (10542, 0, 'Parlamentarische Gruppe')]'.  Aborting.